site_name: Peer5 Docs
theme_dir: 'cinder'
repo_url: https://github.com/peer5/peer5-docs
pages:
- Home: 'index.md'
- Overview: 'overview.md'
- Players:
    - 'Clappr': 'players/clappr.md'
    - 'VideoJS': 'players/videojs.md'
    - 'JWPlayer': 'players/jwplayer-7.md'
    - 'Shaka Player': 'players/shaka-player.md'
- Guides:
    - 'HLS with Nimble': 'guides/hls-with-nimble.md'
    - 'How to optimize Wowza server': 'guides/how-to-optimize-wowza-server.md'
    - 'Setting up HLS live streaming server using NGINX': 'guides/setting-up-hls-live-streaming-server-using-nginx.md'
    - 'Configure CORS headers': 'guides/cors.md'