site_name: Peer5 Docs
theme_dir: 'cinder'
repo_url: https://github.com/peer5/peer5-docs
site_url: https://docs.peer5.com
site_description: 'Peer5 documentation'
site_favicon: favicon.ico
google_analytics: ['UA-30916189-1', 'docs.peer5.com']
pages:
- Home: 'index.md'
- Overview: 'overview.md'
- FAQ: 'faq.md'
- Players:
    - 'Clappr': 'players/clappr.md'
    - 'VideoJS': 'players/videojs.md'
    - 'JWPlayer': 'players/jwplayer-7.md'
    - 'Flowplayer': 'players/flowplayer.md'
    - 'Shaka Player': 'players/shaka-player.md'
    - 'Kaltura': 'players/kaltura.md'
- Guides:
    - 'HLS with Nimble': 'guides/hls-with-nimble.md'
    - 'How to optimize Wowza server': 'guides/how-to-optimize-wowza-server.md'
    - 'Setting up HLS live streaming server using NGINX': 'guides/setting-up-hls-live-streaming-server-using-nginx.md'
    - 'Configure CORS headers': 'guides/cors.md'
    - 'Configuring the Peer5 libarary': 'guides/configuring-peer5.md'
- APIs:
    - 'stats': 'apis/get-stats.md'